### ISSUE TITLE
Typo HTTP

### ISSUE THREAD

**Issue by kevanantha** [evilfactorylabs/learning-resources#1]
Change transform to transfer

<img width="590" alt="image" src="https://user-images.githubusercontent.com/31406355/80282812-ad642e00-873d-11ea-8595-d9d924d1eaa9.png">

**Comment by faultables** [comment]
Oops thank you for your caught!

Send some PR?

**Comment by kevanantha** [comment]
> Oops thank you for your caught!
> 
> Send some PR?

Okay
