### ISSUE TITLE
Add "Ops School Curriculum"

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/learning-resources#11]
Anyone please add [Ops School Curriculum](https://www.opsschool.org/introduction.html) as it has comprehensive resource and is pretty good for anyone interested in becoming a sysadmin.

Suggestion: add to "Fundamentals" section pwiiis 🥺

**Comment by r17x** [comment]
Could you make it happen!

**Comment by faultables** [comment]
1yr and still counting

**Comment by faultables** [comment]
bang RiN bisa mintol dibuat MR kali ya? kebetulan saya masih lupa passphrase gpg @r17x

**Comment by r17x** [comment]
@faultables via web aja (editor web) itu auto verified kok

**Comment by faultables** [comment]
ga mau
